web:
  build: .
  ports:
    - "8000:80"
  links:
    - db
  volumes:
    - .:/code
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - 8080:80
    links:
      - db
db:
  image: "mysql:5"
  volumes:
    - ./mysql:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: phpapptest
    MYSQL_DATABASE: phpapp